kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: datastore

spec:
  replicas: 1
  template:
    metadata:
      name: datastore
      labels:
        app: datastore
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.2-alpine
          imagePullPolicy: IfNotPresent
        - name: api
          image: datastore-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          

#apiVersion: "v1"
#kind: Deployment
#metadata:
#name: datastore
#spec:
#replicas: 1
#spec:
#containers:
#- name: postgres
#image: postgres:9.6.2-alpine
#env:
#- name: "POSTGRES_PASSWORD"
#value: "postgres"
#- name: api
#image: datastore-api
#ports:
#- containerPort: 8080




