kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: datastore
spec:
  replicas: 1
  template:
    metadata:
      name: datastore
      labels:
        app: datastore
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.3-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: datastore
          ports:
            - containerPort: 5432
        - name: datastore
          image: nexus.foundery.club/foundery/datastore:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

      imagePullSecrets:
        - name: dockerprivateregistrykey
