apiVersion: v1
kind: Service
metadata:
  labels:
    app: datastore
  name: datastore
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: datastore

#apiVersion: v1
#kind: Service
#metadata:
#name: datastore
#labels:
#app: datastore
#spec:
#selector:
#app: datastore
#ports:
#- name: postgres
#port: 5432
#protocol: TCP
      #targetPort: 5432
      #- name: api
      #port: 8080
      #protocol: TCP
      #targetPort: 8080

      #type: LoadBalancer


