kind: Service
apiVersion: v1
metadata:
  labels:
    app: datastore
  name: datastore
spec:
  selector:
    app: datastore
  ports:
    - name: datastore
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
